import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, ArrowRight, Brush, Check, ChevronDown, ChevronRight, CircleHelp, Download, Droplets, Eraser, Eye, EyeOff, FileBox, Grid2X2, Hand, ImagePlus, Layers, Lightbulb, LockKeyhole, Maximize, Minus, MoreHorizontal, MousePointer2, Palette, Pipette, Plus, Redo2, Settings2, SlidersHorizontal, Sparkles, Sun, Trash2, Undo2, X } from 'lucide-react';
import { PaintingEngine, type PaintSettings, type PaintLayer } from './painting';
import './index.css';

const COLORS = ['#3159ad','#83a5bd','#9da58b','#e9c785','#c88065','#eee7d7','#464943'];
const PRESETS = ['Round','Flat','Filbert','Watercolor','Airbrush','Palette knife'];
const initialSettings: PaintSettings = { tool:'brush',brush:'Round',color:COLORS[0],size:32,opacity:100,flow:65,wetness:72,viscosity:58,pressure:true,roughness:36 };
function BrushMark({type,color='#535653'}:{type:string;color?:string}) { return <svg viewBox="0 0 90 35" className={`brush-mark brush-${type.toLowerCase().replace(' ','-')}`}><defs><filter id={`blur-${type.replace(' ','')}`}><feGaussianBlur stdDeviation={type==='Airbrush'?3:type==='Watercolor'?1.1:0}/></filter></defs><g filter={`url(#blur-${type.replace(' ','')})`} fill={color}><path d={type==='Palette knife'?'M10 26 65 7 80 10 76 15 19 29Z':type==='Flat'?'M12 21 67 7 77 17 20 30Z':type==='Filbert'?'M15 25C-1 16 62 7 72 8S88 21 69 25 22 32 15 25':type==='Watercolor'?'M12 22Q5 11 28 13T72 8Q86 17 72 24T25 28Z':'M11 25C3 17 33 16 49 10S83 5 79 14 49 25 30 28 16 30 11 25Z'} opacity={type==='Watercolor'?.5:1}/><path d="M13 24Q40 17 76 12M18 27Q44 20 72 17M20 20 62 10" fill="none" stroke="#fff" strokeWidth=".6" opacity=".28"/></g></svg> }
function Slider({label,value,onChange,suffix='%',min=0,max=100,icon}:{label:string;value:number;onChange:(n:number)=>void;suffix?:string;min?:number;max?:number;icon?:React.ReactNode}) {return <div className="slider-control"><div className="slider-label"><span>{icon}{label}</span><span className="slider-value">{value}<small>{suffix}</small></span></div><input aria-label={label} type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)} style={{'--fill':`${(value-min)/(max-min)*100}%`} as React.CSSProperties}/></div>}
function App() {
  const host=useRef<HTMLDivElement>(null), engine=useRef<PaintingEngine|null>(null), modelInput=useRef<HTMLInputElement>(null), imageInput=useRef<HTMLInputElement>(null);
  const [settings,setSettings]=useState(initialSettings), [layers,setLayers]=useState<PaintLayer[]>([]), [activeLayer,setActiveLayer]=useState(2);
  const [project,setProject]=useState('Ceramic study'),[editingName,setEditingName]=useState(false),[modal,setModal]=useState<string|null>(null),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[painted,setPainted]=useState(false);
  const [tab,setTab]=useState('Paint'),[palette,setPalette]=useState(COLORS),[reference,setReference]=useState<string|null>(null),[image,setImage]=useState<HTMLImageElement|null>(null),[referenceColors,setReferenceColors]=useState<string[]>([]);
  const [grid,setGrid]=useState(true),[light,setLight]=useState('Studio'),[layerMenu,setLayerMenu]=useState(false),[paletteMenu,setPaletteMenu]=useState(false),[tip,setTip]=useState(true),[cursor,setCursor]=useState({x:0,y:0,visible:false}),[modelName,setModelName]=useState('Ceramic vase'),[finish,setFinish]=useState('Satin');
  const toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  function notify(text:string){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3500);}
  function sync(){if(engine.current){setLayers([...engine.current.layers]);setActiveLayer(engine.current.activeLayer);}}
  useEffect(()=>{if(!host.current)return;try {const e=new PaintingEngine(host.current,initialSettings,sync,()=>{setPainted(true);},color=>{setSettings(s=>({...s,color,tool:'brush'}));notify('Color picked from the model');});engine.current=e;e.setTool('brush');sync();return()=>{e.dispose();clearTimeout(toastTimer.current);};}catch{notify('Your browser needs WebGL to display the 3D canvas.');}},[]);
  useEffect(()=>{if(engine.current){engine.current.settings={...settings};engine.current.setTool(settings.tool);engine.current.setRoughness(settings.roughness/100);}},[settings]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();undo(e.shiftKey);return;}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();setModal('export');return;}const keys:Record<string,string>={b:'brush',e:'erase',i:'eyedropper',h:'orbit',m:'blend'};if(keys[e.key])update('tool',keys[e.key]);if(e.key==='[')setSettings(s=>({...s,size:Math.max(1,s.size-4)}));if(e.key===']')setSettings(s=>({...s,size:Math.min(100,s.size+4)}));if(e.key==='Escape')setModal(null);};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
  function update<K extends keyof PaintSettings>(key:K,value:PaintSettings[K]){setSettings(s=>({...s,[key]:value}));}
  function undo(redo=false){if(engine.current?.undo(redo)){setPainted(true);notify(redo?'Stroke restored':'Stroke undone');}else notify(redo?'Nothing to redo yet':'Your canvas is ready for its first stroke');}
  async function importModel(file?:File){if(!file)return;if(!file.name.toLowerCase().endsWith('.glb')){notify('Please choose a .glb model');return;}setBusy(true);try{await engine.current?.importGLB(file);setModelName(file.name.replace(/\.glb$/i,''));setProject(file.name.replace(/\.glb$/i,''));setModal(null);setPainted(false);notify('Model imported. Make it your own.');}catch(e){notify(e instanceof Error?e.message:'Could not import this model');}finally{setBusy(false);if(modelInput.current)modelInput.current.value='';}}
  function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function exportModel(){if(!engine.current)return;setBusy(true);try{const result=await engine.current.exportGLB();saveBlob(new Blob([result as ArrayBuffer],{type:'model/gltf-binary'}),`${project||'Untitled'}.glb`);setPainted(false);setModal(null);notify('Your painted model is exported');}catch{notify('Export could not complete. Please try again.');}finally{setBusy(false);}}
  function exportImage(){if(!engine.current)return;const a=document.createElement('a');a.href=engine.current.screenshot();a.download=`${project}.png`;a.click();notify('Studio image exported');setModal(null);}
  function loadImage(file?:File){if(!file)return;if(!file.type.startsWith('image/')){notify('Choose a PNG, JPG, or WebP image');return;}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{setReference(url);setImage(img);const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0,64,64);const data=ctx.getImageData(0,0,64,64).data;const buckets=new Map<string,{sum:number[];n:number}>();for(let i=0;i<data.length;i+=4){if(data[i+3]<128)continue;const key=[data[i],data[i+1],data[i+2]].map(n=>Math.round(n/40)).join(',');const b=buckets.get(key)||{sum:[0,0,0],n:0};b.n++;for(let k=0;k<3;k++)b.sum[k]+=data[i+k];buckets.set(key,b);}setReferenceColors([...buckets.values()].sort((a,b)=>b.n-a.n).slice(0,7).map(b=>'#'+b.sum.map(n=>Math.round(n/b.n).toString(16).padStart(2,'0')).join('')));setModal('reference');};img.onerror=()=>notify('This image could not be read');img.src=url;}
  function changeLayer(id:number,patch:Partial<PaintLayer>){if(!engine.current)return;engine.current.layers=engine.current.layers.map(l=>l.id===id?{...l,...patch}:l);engine.current.composite();sync();setPainted(true);}
  const selectedLayer=layers.find(l=>l.id===activeLayer);
  const tools=[{id:'brush',icon:Brush,label:'Paint brush',key:'B'},{id:'blend',icon:Droplets,label:'Blend paint',key:'M'},{id:'erase',icon:Eraser,label:'Eraser',key:'E'},{id:'eyedropper',icon:Pipette,label:'Pick color',key:'I'},{id:'orbit',icon:Hand,label:'Orbit model',key:'H'}];
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href="#" onClick={e=>e.preventDefault()} aria-label="Forma home"><span className="brand-symbol"><svg viewBox="0 0 32 32"><path d="M6 27V14A10 10 0 0 1 16 4h11v8H17a3 3 0 0 0-3 3v1h11v8H14v3Z" fill="currentColor"/><circle cx="24" cy="27" r="3" fill="currentColor"/></svg></span>forma<span className="brand-dot">.</span><span className="studio-label">3D STUDIO</span></a>
      <div className="project-title">{editingName?<input autoFocus value={project} onChange={e=>setProject(e.target.value)} onBlur={()=>setEditingName(false)} onKeyDown={e=>e.key==='Enter'&&setEditingName(false)}/>:<button onClick={()=>setEditingName(true)}>{project}<ChevronDown size={13}/></button>}<span className="project-state" title={painted?'There are unexported changes':'Ready to paint'}><span className={painted?'unsaved':''}/>{painted?'Unsaved changes':'All set to create'}</span></div>
      <nav className="header-tabs">{['Paint','Materials'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);if(t==='Materials')setModal('materials');}}>{t}</button>)}</nav>
      <div className="header-actions"><button className="icon-button help-button" title="Help & keyboard shortcuts" onClick={()=>setModal('help')}><CircleHelp size={19}/></button><span className="header-divider"/><button className="button import-button" onClick={()=>setModal('import')}><ArrowUpFromLine size={15}/>Import<span className="optional"> model</span></button><button className="button primary" onClick={()=>setModal('export')}><ArrowDownToLine size={15}/>Export<ChevronDown size={13}/></button><div className="avatar" title="Your personal workspace">JD</div></div>
    </header>
    <main className="studio-layout">
      <aside className="left-sidebar"><div className="panel-heading"><span><Brush size={16}/>Brush studio</span><button className="icon-button small" title="Reset brush settings" onClick={()=>{setSettings(s=>({...initialSettings,color:s.color}));notify('Brush settings reset');}}><SlidersHorizontal size={15}/></button></div>
        <div className="sidebar-scroll"><section className="brush-section"><div className="section-label">YOUR MEDIUM<span className="tiny-tag">6 brushes</span></div><div className="medium-select"><span className="medium-icon"><Droplets size={16}/></span><select aria-label="Paint medium" onChange={e=>{if(e.target.value==='Watercolor'){update('brush','Watercolor');update('wetness',90);update('viscosity',20);}else if(e.target.value==='Acrylic'){update('viscosity',85);update('wetness',35);}else{update('wetness',72);update('viscosity',58);}}}><option>Oil paint</option><option>Watercolor</option><option>Acrylic</option></select><ChevronDown size={13}/></div>
        <div className="brush-grid">{PRESETS.map(b=><button key={b} className={`brush-preset ${settings.brush===b?'selected':''}`} onClick={()=>{update('brush',b);update('tool','brush');}}><BrushMark type={b} color={settings.brush===b?'#bc6d46':undefined}/><span>{b}</span>{settings.brush===b&&<span className="selected-dot"/>}</button>)}</div></section>
        <section className="settings-section"><div className="section-label">BRUSH SETTINGS<Settings2 size={13}/></div><Slider label="Size" value={settings.size} suffix="px" min={1} onChange={v=>update('size',v)}/><Slider label="Opacity" value={settings.opacity} onChange={v=>update('opacity',v)}/><Slider label="Flow" value={settings.flow} onChange={v=>update('flow',v)}/><div className="toggle-row"><span><MousePointer2 size={13}/>Pen pressure</span><button role="switch" aria-checked={settings.pressure} aria-label="Pen pressure" className={`toggle ${settings.pressure?'on':''}`} onClick={()=>update('pressure',!settings.pressure)}><span/></button></div><div className="pressure-caption">A lighter touch. A softer stroke.</div></section>
        <section className="settings-section paint-behavior"><div className="section-label">PAINT BEHAVIOR<span className="live-tag"><span/>LIVE</span></div><Slider label="Wetness" value={settings.wetness} onChange={v=>update('wetness',v)}/><div className="range-captions"><span>Dry</span><span>Fluid</span></div><Slider label="Viscosity" value={settings.viscosity} onChange={v=>update('viscosity',v)}/><div className="range-captions"><span>Thin</span><span>Thick</span></div><div className="physics-note"><Sparkles size={15}/><span>Real paint. More possibility.<br/><small>Blend freely. Stay in control.</small></span></div></section>
        </div><button className="reference-button" onClick={()=>setModal('reference')}><span className="reference-icon"><ImagePlus size={19}/></span><span>Reference to reality<small>Bring an image. Find inspiration.</small></span><ChevronRight size={15}/></button>
      </aside>
      <section className="workspace"><div className="workspace-topbar"><div className="scene-title"><FileBox size={14}/><span>{modelName}</span><span className="scene-dot">·</span><span className="muted">3D canvas</span></div><div className="view-controls"><button onClick={()=>{const v=light==='Studio'?'Warm':'Studio';setLight(v);if(engine.current)engine.current.renderer.toneMappingExposure=v==='Warm'?1.65:1.25;}} title="Switch studio lighting"><Sun size={14}/><span>{light} light</span><ChevronDown size={11}/></button><button className={grid?'enabled':''} title="Toggle floor grid" onClick={()=>{setGrid(!grid);if(engine.current)engine.current.grid.visible=!grid;}}><Grid2X2 size={15}/></button></div></div>
        <div className="canvas-host" ref={host} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setCursor({x:e.clientX-r.left,y:e.clientY-r.top,visible:true});}} onPointerLeave={()=>setCursor(c=>({...c,visible:false}))}/>
        {cursor.visible&&settings.tool!=='orbit'&&<div className="brush-cursor" style={{left:cursor.x,top:cursor.y+43,width:Math.max(8,settings.size*.65),height:Math.max(8,settings.size*.65),borderColor:settings.tool==='erase'?'#b55c48':'#ffffffb0'}}/>}
        <div className="floating-toolbar"><div className="tools">{tools.map(t=><button key={t.id} className={settings.tool===t.id?'active':''} title={`${t.label} (${t.key})`} aria-label={t.label} onClick={()=>update('tool',t.id)}><t.icon size={19}/>{settings.tool===t.id&&<span className="tool-dot"/>}</button>)}</div><span className="toolbar-separator"/><button className="undo-btn" title="Undo (Ctrl+Z)" onClick={()=>undo()}><Undo2 size={17}/></button><button className="undo-btn" title="Redo (Ctrl+Shift+Z)" onClick={()=>undo(true)}><Redo2 size={17}/></button></div>
        <div className="canvas-view-label"><span className="view-dot"/>Perspective<ChevronDown size={11}/></div>
        <div className="axis-gizmo" title="Reset camera" onClick={()=>engine.current?.resetView()} role="button" tabIndex={0} onKeyDown={e=>e.key==='Enter'&&engine.current?.resetView()}><div className="axis-line axis-y"/><div className="axis-line axis-x"/><div className="axis-line axis-z"/><span className="axis-letter y">Y</span><span className="axis-letter x">X</span><span className="axis-letter z">Z</span><span className="axis-center"/></div>
        <div className="canvas-bottom"><div className="palette-tray"><button className="current-paint" title="Choose paint color" onClick={()=>setPaletteMenu(!paletteMenu)}><span style={{background:settings.color}}/><ChevronDown size={11}/></button><span className="palette-separator"/>{palette.map((c,i)=><button key={`${c}${i}`} className={`paint-swatch ${settings.color===c?'active':''}`} style={{'--swatch':c} as React.CSSProperties} title={c} aria-label={`Select color ${c}`} onClick={()=>update('color',c)}/>) }<button className="add-color" title="Add current color to palette" onClick={()=>{setPalette(p=>p.includes(settings.color)?p:[...p.slice(-7),settings.color]);notify('Color added to your palette');}}><Plus size={17}/></button>{paletteMenu&&<div className="palette-popover"><b>Your paint color</b><input type="color" value={settings.color} onChange={e=>update('color',e.target.value)}/><span>{settings.color.toUpperCase()}</span></div>}</div><div className="palette-caption">The coastal collection<span>·</span><button onClick={()=>setModal('reference')}>Create a palette<ArrowRight size={11}/></button></div></div>
        {tip&&<div className="canvas-tip"><span className="tip-icon"><Sparkles size={16}/></span><div>A fresh perspective.<p>Paint a little outside the canvas.</p></div><button aria-label="Dismiss tip" onClick={()=>setTip(false)}><X size={12}/></button></div>}
        <div className="zoom-controls"><button title="Zoom out" onClick={()=>engine.current?.zoom(1.12)}><Minus size={14}/></button><button className="zoom-reset" title="Reset view" onClick={()=>engine.current?.resetView()}>Fit</button><button title="Zoom in" onClick={()=>engine.current?.zoom(.88)}><Plus size={14}/></button><span/><button title="Reset camera" onClick={()=>engine.current?.resetView()}><Maximize size={14}/></button></div>
        <div className="workspace-footer"><span><span className="keycap">Space</span> + drag to orbit</span><span><span className="mouse-icon"/>Scroll to zoom</span><span className="footer-right"><span className="green-dot"/>Stylus ready</span></div>
      </section>
      <aside className="right-sidebar"><div className="panel-heading"><span><Palette size={16}/>Color</span><button className="icon-button small" title="Pick a color from model" onClick={()=>update('tool','eyedropper')}><Pipette size={15}/></button></div><section className="color-section"><div className="color-square" style={{'--chosen':settings.color} as React.CSSProperties} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;const h=parseInt(settings.color.slice(1),16);const rgb=[h>>16,(h>>8)&255,h&255].map(v=>Math.round((255*(1-x)+v*x)*(1-y)));update('color','#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join(''));}}><span className="color-picker-point"/></div><input className="hue-slider" type="range" min="0" max="360" defaultValue="224" aria-label="Color hue" onChange={e=>{const h=+e.target.value/60,c=.68,x=c*(1-Math.abs(h%2-1));const rgb=h<1?[c,x,0]:h<2?[x,c,0]:h<3?[0,c,x]:h<4?[0,x,c]:h<5?[x,0,c]:[c,0,x];update('color','#'+rgb.map(v=>Math.round((v+.16)*255).toString(16).padStart(2,'0')).join(''));}}/><div className="color-values"><label className="color-hex"><span>HEX</span><input aria-label="Hex color" key={settings.color} defaultValue={settings.color.toUpperCase()} onBlur={e=>{const value=e.target.value.startsWith('#')?e.target.value:'#'+e.target.value;if(/^#[\da-f]{6}$/i.test(value))update('color',value);else{e.target.value=settings.color.toUpperCase();notify('Enter a six-digit hex color, like #3159AD');}}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onClick={e=>e.currentTarget.select()}/><input type="color" aria-label="Open color picker" value={settings.color} onChange={e=>update('color',e.target.value)}/></label><button className="opacity-chip" title="Reset brush opacity" onClick={()=>update('opacity',100)}>{settings.opacity}<span>%</span></button></div><div className="recent-label">Recently used</div><div className="recent-colors">{['#3159ad','#6d8499','#adbcbb','#d9b89c','#c88065','#e9c785','#eee7d7','#fffdf7'].map(c=><button key={c} aria-label={`Use ${c}`} style={{background:c}} onClick={()=>update('color',c)}/>)}</div></section>
        <section className="layers-section"><div className="panel-heading"><span><Layers size={16}/>Layers<span className="count-badge">{layers.length}</span></span><div><button className="icon-button small" title="Add paint layer" onClick={()=>engine.current?.addLayer()}><Plus size={17}/></button><button className="icon-button small" title="Layer options" onClick={()=>setLayerMenu(!layerMenu)}><MoreHorizontal size={17}/></button></div></div><div className="layer-blending"><span>Normal<ChevronDown size={11}/></span><label>Opacity<input aria-label="Layer opacity" type="number" min="0" max="100" value={selectedLayer?.opacity??100} onChange={e=>changeLayer(activeLayer,{opacity:Math.max(0,Math.min(100,+e.target.value))})}/>%</label></div><div className="layer-list">{layers.map(l=><div key={l.id} className={`layer-row ${activeLayer===l.id?'selected':''}`} onClick={()=>{if(engine.current)engine.current.activeLayer=l.id;setActiveLayer(l.id);}}><button className="layer-eye" aria-label={l.visible?'Hide '+l.name:'Show '+l.name} onClick={e=>{e.stopPropagation();changeLayer(l.id,{visible:!l.visible});}}>{l.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><div className={`layer-thumb ${l.locked?'base-thumb':''}`}>{!l.locked&&<BrushMark type="Round" color="#3159ad"/>}</div><div className="layer-name">{l.name}<small>{l.locked?'Base material':'Paint layer'}</small></div>{l.locked?<LockKeyhole size={12}/>:<span className="layer-active-dot"/>}</div>)}</div>{layerMenu&&<div className="layer-menu"><button disabled={selectedLayer?.locked} onClick={()=>{if(!engine.current)return;engine.current.layers=engine.current.layers.filter(l=>l.id!==activeLayer);engine.current.activeLayer=engine.current.layers.find(l=>!l.locked)?.id??1;engine.current.composite();sync();setLayerMenu(false);}}><Trash2 size={14}/>Delete selected layer</button><button onClick={()=>{engine.current?.addLayer();setLayerMenu(false);}}><Plus size={14}/>New paint layer</button></div>}<button className="add-layer-button" onClick={()=>engine.current?.addLayer()}><Plus size={14}/>Add a layer</button></section>
        <section className="surface-section"><div className="section-label">SURFACE<SlidersHorizontal size={13}/></div><button className="material-card" onClick={()=>setModal('materials')}><span className="material-sphere"/><span>Ceramic<small>{finish} finish</small></span><ChevronRight size={15}/></button><Slider label="Roughness" value={settings.roughness} onChange={v=>update('roughness',v)}/></section>
        <div className="studio-note"><span className="studio-note-icon"><Lightbulb size={17}/></span><p>Made for the way you paint.<br/><span>No drying time. No wrong turns.</span></p></div>
      </aside>
    </main><footer className="statusbar"><span className="status-brand"><span className="green-dot"/>Everything you need. Nothing in your way.</span><span>UV texture <b>1024 × 1024</b><span className="status-separator"/>WebGL 2<span className="status-separator"/><button onClick={()=>setModal('help')}>Keyboard shortcuts<CircleHelp size={12}/></button></span><span className="version">FORMA v1.0</span></footer>
    <input ref={modelInput} type="file" accept=".glb" hidden onChange={e=>importModel(e.target.files?.[0])}/><input ref={imageInput} type="file" accept="image/*" hidden onChange={e=>loadImage(e.target.files?.[0])}/>
    {toast&&<div className="toast"><span><Check size={15}/></span>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={14}/></button></div>}
    {modal&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget){setModal(null);setTab('Paint');}}}><div className={`modal ${modal==='reference'?'reference-modal':''}`}><button className="modal-close icon-button" aria-label="Close dialog" onClick={()=>{setModal(null);setTab('Paint');}}><X size={20}/></button>
      {modal==='import'&&<><div className="modal-icon"><FileBox size={25}/></div><h2>A new shape for your ideas.</h2><p>Bring your own model into the studio. Your materials and UVs come with it.</p><button className="dropzone" onClick={()=>modelInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();importModel(e.dataTransfer.files[0]);}}><ArrowUpFromLine size={28}/><strong>{busy?'Preparing your model…':'Drop your GLB model here'}</strong><span>or click to browse your files</span><small>.GLB · UV-mapped models</small></button><div className="info-note"><Lightbulb size={16}/><span>Importing starts a new painting. Export your current work first if you’d like to keep it.</span></div></>}
      {modal==='export'&&<><div className="modal-icon"><Download size={25}/></div><h2>Take your creation with you.</h2><p>Your model. Your colors. Ready for whatever comes next.</p><label className="field-label">FILE NAME<input value={project} onChange={e=>setProject(e.target.value)}/></label><div className="export-detail"><FileBox size={27}/><div><b>Painted 3D model</b><span>GLB · embedded 1024px paint textures</span></div><Check size={18}/></div><button className="button primary modal-primary" disabled={busy} onClick={exportModel}><Download size={17}/>{busy?'Packing your colors…':'Export GLB model'}</button><button className="button secondary-full" onClick={exportImage}><ImagePlus size={16}/>Save canvas as PNG</button><small className="modal-footnote">Visible layers are flattened into the exported texture.</small></>}
      {modal==='reference'&&<><div className="modal-icon"><Sparkles size={25}/></div><h2>Reference to reality.</h2><p>Turn an image you love into a palette, or wrap its colors around your model as a new paint layer.</p>{reference?<div className="reference-preview"><img src={reference} alt="Your imported art reference"/><button className="button" onClick={()=>imageInput.current?.click()}><ImagePlus size={14}/>Replace image</button></div>:<button className="dropzone" onClick={()=>imageInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();loadImage(e.dataTransfer.files[0]);}}><ImagePlus size={29}/><strong>Bring a little inspiration</strong><span>Drop an image or click to browse</span><small>PNG, JPG, or WebP</small></button>}{reference&&<><div className="section-label extracted-label">EXTRACTED FROM YOUR IMAGE</div><div className="extracted-colors">{referenceColors.map(c=><button key={c} title={c} style={{background:c}} onClick={()=>update('color',c)}/>)}</div><button className="button primary modal-primary" onClick={()=>{setPalette(referenceColors);update('color',referenceColors[0]||COLORS[0]);setModal(null);notify('Your image-inspired palette is ready');}}><Palette size={17}/>Use this palette</button><button className="button secondary-full" onClick={()=>{if(image){engine.current?.applyImage(image);setModal(null);notify('Color study added as an editable layer');}}}><Sparkles size={16}/>Create a color study on my model</button><small className="modal-footnote">Softened, full-color image transfer using your model’s UV map.</small></>}</>}
      {modal==='materials'&&<><div className="modal-icon"><Sun size={25}/></div><h2>Give your paint a feeling.</h2><p>Find the perfect surface finish. Your brushwork stays exactly where you left it.</p><div className="finish-options">{[{name:'Matte',roughness:85},{name:'Satin',roughness:36},{name:'Glazed',roughness:12}].map(f=><button key={f.name} className={finish===f.name?'selected':''} onClick={()=>{setFinish(f.name);update('roughness',f.roughness);}}><span className={`material-sphere finish-${f.name.toLowerCase()}`}/><b>{f.name}</b><small>{f.roughness}% roughness</small>{finish===f.name&&<Check size={16}/>}</button>)}</div><Slider label="Surface roughness" value={settings.roughness} onChange={v=>update('roughness',v)}/><button className="button primary modal-primary" onClick={()=>{setModal(null);setTab('Paint');}}>Back to painting<ArrowRight size={16}/></button></>}
      {modal==='help'&&<><div className="modal-icon"><Brush size={25}/></div><h2>A little guidance. Then, go create.</h2><p>Paint directly on your model with a mouse or pressure-sensitive stylus. Right-drag to see a new side.</p><div className="shortcut-list">{[['Paint brush','B'],['Blend / smudge','M'],['Erase paint','E'],['Pick a color','I'],['Orbit the model','Space + drag'],['Change brush size','[ / ]'],['Undo a stroke','Ctrl / ⌘ + Z'],['Export your creation','Ctrl / ⌘ + S']].map(([a,b])=><div key={a}><span>{a}</span><kbd>{b}</kbd></div>)}</div><div className="info-note"><Droplets size={17}/><span>Wetness softens edges; viscosity controls pigment build-up. Blend samples nearby pigment. This is a responsive artistic simulation, not a physical fluid solver.</span></div><button className="button primary modal-primary" onClick={()=>setModal(null)}>Let’s make something<ArrowRight size={16}/></button></>}
    </div></div>}
  </div>;
}
export default App;
